spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://${mysql:lv3-mysqldb-ansoo.ccxmcbwnnwze.us-east-1.rds.amazonaws.com}:3306/TestDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #url: jdbc:mysql://${mysql:hellogptvmysql.cdillw7s0dxx.ap-northeast-2.rds.amazonaws.com}:3306/FromUser?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: admin
    #password: 8659653314
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWD}